<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"/>
    <meta name="keywords" content="Магазин, люстры, освещение">
    <meta name="description" content="Сайт люстр">
    <title>Тестовое задания DIOL</title>
    <link rel="stylesheet" type="text/css" href="../css/styles.css" />
    <link href="https://fonts.googleapis.com/css?family=Bellota+Text&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>
  <body>
    <header>
        <h1 class="headline">Название сайта</h1>
    </header>
